package org.iel.code_sismatic.model.enuns;

public enum AreaSistemaEnum {
	ADICIONAR_CUPONS, 
	RESGATAR_CUPONS, 
	VISUALIZAR_CUPONS, 
	ADICIONAR_CONSUMIDOR, 
	VISUALIZAR_CONSUMIDOR, 
	EDITAR_CONSUMIDOR, 
	ADICIONAR_USUARIO, 
	VISUALIZAR_USUARIO, 
	EDITAR_USUARIO, 
	INATIVAR_USUARIO
}