package org.iel.projeto_integrador.model.enuns;

public enum PermissaoEnum {
	ADICIONAR_USUARIO,
	EDITAR_USUARIO,
	INATIVAR_USUARIO,
	ADICIONAR_CUPONS,
	VISUALIZAR_CUPONS,
	RESGATAR_CUPONS,
	ADICIONAR_CONSUMIDOR,
	VISUALIZAR_CONSUMIDOR,
	VISUALIZAR_CONFIGURACOES,
	ALTERAR_CONFIGURACOES,
	ACESSAR_MINHA_CONTA,
	CRIAR_CHAMADOS,
	FINALIZAR_CHAMADOS,
	VISUALIZAR_CHAMADOS,
	VISUALIZAR_PARAMETROS,
	EDITAR_PARAMETROS
}